CREATE TABLE IF NOT EXISTS softs AS (
  SELECT NOMLOG AS nomsoft, version, prix
  FROM LOGICIEL
);
CREATE TABLE IF NOT EXISTS PCSeuls AS (
  SELECT NPOSTE AS nP, NOMPOSTE AS nomP, ad, INDIP AS seg, TYPEPOSTE AS typeP, NSALLE AS salle
  FROM POSTE
);